[package]
name = "simple_timer"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
rusqlite = "0.24.1"
chrono = "0.4.19"
dirs-next = "1.0.2"